import type { Metadata } from "next";
import "./styles/globals.css";
import { Inter, Great_Vibes } from 'next/font/google'
import NavigationWrapper from "./component/NavigationWrapper";
import ReduxProvider from "@/redux/features/provider";
import Footer from './component/Footer'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-great-vibes',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${greatVibes.variable}`}>
      <body>
        <ReduxProvider>
          <NavigationWrapper />
          {children}
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}
